
lsi: false
safe: true
source: ${PWD}
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

layout: layout
title: Yo blog
theme: jekyll-theme-cayman


