
lsi: false
safe: true
source: ${PWD}/post
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

layouts: ${PWD}
title: "Yo blog"
theme: jekyll-theme-cayman


