
lsi: false
safe: true
source: ${PWD}
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

layouts_dir: ./layout
title: Blogging Like a Hacker
theme: jekyll-theme-cayman


